#!/usr/bin/env bash
# Shebang for better file detection
#### libre module config
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

[[ -n "$LIBRE_DEPS" ]] || LIBRE_DEPS="libretech-gpio libretech-dtoverlay"
