#!/usr/bin/env bash
#### Libre DNS workaround
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces

## Source error handling, leave this in place
set -Ee

## Set LC_ALL to prevent errors
export LC_ALL=C

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Libre LePotato DNS Workaround ... [CLEANUP]"

## Step 1: remove temporary DNS servers
rm -f /etc/resolv.conf
## END Step 1
