#!/usr/bin/env bash


set -Eex


## Set LC_ALL to prevent errors
export LC_ALL=C

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_red "Libre DEBUG script"

# cat /etc/apt/sources.list

# ls /etc/apt/sources.list.d

echo "nameserver 1.1.1.1" > /etc/resolv.conf

ping -c1 deb.debian.org

